/* tslint:disable */
/* eslint-disable */
/**
 * FormulaOne.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDriverRequest
 */
export interface CreateDriverRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDriverRequest
     */
    FirstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDriverRequest
     */
    LastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateDriverRequest
     */
    DriverNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateDriverRequest
     */
    DateOfBirth?: Date;
}

/**
 * Check if a given object implements the CreateDriverRequest interface.
 */
export function instanceOfCreateDriverRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateDriverRequestFromJSON(json: any): CreateDriverRequest {
    return CreateDriverRequestFromJSONTyped(json, false);
}

export function CreateDriverRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDriverRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'FirstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'LastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'DriverNumber': !exists(json, 'driverNumber') ? undefined : json['driverNumber'],
        'DateOfBirth': !exists(json, 'dateOfBirth') ? undefined : (new Date(json['dateOfBirth'])),
    };
}

export function CreateDriverRequestToJSON(value?: CreateDriverRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.FirstName,
        'lastName': value.LastName,
        'driverNumber': value.DriverNumber,
        'dateOfBirth': value.DateOfBirth === undefined ? undefined : (value.DateOfBirth.toISOString()),
    };
}

