/* tslint:disable */
/* eslint-disable */
/**
 * FormulaOne.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDriverAchievementRequest
 */
export interface CreateDriverAchievementRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDriverAchievementRequest
     */
    DriverId?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDriverAchievementRequest
     */
    WorldChampionship?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDriverAchievementRequest
     */
    FastestLap?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDriverAchievementRequest
     */
    PolePosition?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDriverAchievementRequest
     */
    Wins?: number;
}

/**
 * Check if a given object implements the CreateDriverAchievementRequest interface.
 */
export function instanceOfCreateDriverAchievementRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateDriverAchievementRequestFromJSON(json: any): CreateDriverAchievementRequest {
    return CreateDriverAchievementRequestFromJSONTyped(json, false);
}

export function CreateDriverAchievementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDriverAchievementRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DriverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'WorldChampionship': !exists(json, 'worldChampionship') ? undefined : json['worldChampionship'],
        'FastestLap': !exists(json, 'fastestLap') ? undefined : json['fastestLap'],
        'PolePosition': !exists(json, 'polePosition') ? undefined : json['polePosition'],
        'Wins': !exists(json, 'wins') ? undefined : json['wins'],
    };
}

export function CreateDriverAchievementRequestToJSON(value?: CreateDriverAchievementRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'driverId': value.DriverId,
        'worldChampionship': value.WorldChampionship,
        'fastestLap': value.FastestLap,
        'polePosition': value.PolePosition,
        'wins': value.Wins,
    };
}

