/* tslint:disable */
/* eslint-disable */
/**
 * FormulaOne.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDriverAchievementRequest
 */
export interface UpdateDriverAchievementRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDriverAchievementRequest
     */
    DriverId?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateDriverAchievementRequest
     */
    WorldChampionship?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDriverAchievementRequest
     */
    FastestLap?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDriverAchievementRequest
     */
    PolePosition?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDriverAchievementRequest
     */
    Wins?: number;
}

/**
 * Check if a given object implements the UpdateDriverAchievementRequest interface.
 */
export function instanceOfUpdateDriverAchievementRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateDriverAchievementRequestFromJSON(json: any): UpdateDriverAchievementRequest {
    return UpdateDriverAchievementRequestFromJSONTyped(json, false);
}

export function UpdateDriverAchievementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDriverAchievementRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DriverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'WorldChampionship': !exists(json, 'worldChampionship') ? undefined : json['worldChampionship'],
        'FastestLap': !exists(json, 'fastestLap') ? undefined : json['fastestLap'],
        'PolePosition': !exists(json, 'polePosition') ? undefined : json['polePosition'],
        'Wins': !exists(json, 'wins') ? undefined : json['wins'],
    };
}

export function UpdateDriverAchievementRequestToJSON(value?: UpdateDriverAchievementRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'driverId': value.DriverId,
        'worldChampionship': value.WorldChampionship,
        'fastestLap': value.FastestLap,
        'polePosition': value.PolePosition,
        'wins': value.Wins,
    };
}

