/* tslint:disable */
/* eslint-disable */
/**
 * FormulaOne.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDriverRequest
 */
export interface UpdateDriverRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDriverRequest
     */
    DriverId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDriverRequest
     */
    FirstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateDriverRequest
     */
    LastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateDriverRequest
     */
    DriverNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDriverRequest
     */
    DateOfBirth?: Date;
}

/**
 * Check if a given object implements the UpdateDriverRequest interface.
 */
export function instanceOfUpdateDriverRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateDriverRequestFromJSON(json: any): UpdateDriverRequest {
    return UpdateDriverRequestFromJSONTyped(json, false);
}

export function UpdateDriverRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDriverRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DriverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'FirstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'LastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'DriverNumber': !exists(json, 'driverNumber') ? undefined : json['driverNumber'],
        'DateOfBirth': !exists(json, 'dateOfBirth') ? undefined : (new Date(json['dateOfBirth'])),
    };
}

export function UpdateDriverRequestToJSON(value?: UpdateDriverRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'driverId': value.DriverId,
        'firstName': value.FirstName,
        'lastName': value.LastName,
        'driverNumber': value.DriverNumber,
        'dateOfBirth': value.DateOfBirth === undefined ? undefined : (value.DateOfBirth.toISOString()),
    };
}

